export const DUMMY_LOADS = [
  // ════════════════════════════════════════
  // CHENNAI LOADS
  // ════════════════════════════════════════
  {
    loadId: 'CL001', isNew: true,
    pickupCity: 'Chennai, TN',
    dropCity: 'Bengaluru, KA',
    pickupFullAddress: 'Plot 45, SIPCOT Industrial Park, Irrungattukottai, Chennai 602105',
    dropFullAddress: 'Warehouse 12, Bommasandra Industrial Area, Bengaluru 560099',
    pickupDate: '28 Apr, 10:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Body',
    vehicleSize: '22ft',
    axle: '6 Wheeler',
    weight: 13, distance: 346,
    goodsType: 'Industrial Parts',
    paymentTerms: '80% Advance',
    paymentGuaranteed: true,
    budgetMin: 20000, budgetMax: 24000,
  },
  {
    loadId: 'CL002', isNew: false,
    pickupCity: 'Chennai, TN',
    dropCity: 'Hyderabad, TS',
    pickupFullAddress: 'Gate 3, Ambattur Industrial Estate, Chennai 600058',
    dropFullAddress: 'Plot 22, IDA Uppal, Hyderabad 500039',
    pickupDate: '29 Apr, 08:00 AM',
    vehicleCategory: 'container',
    vehicleType: 'Standard Container',
    vehicleSize: '32ft SXL',
    axle: 'Single Axle',
    weight: 9, distance: 627,
    goodsType: 'FMCG Goods',
    paymentTerms: '100% After Delivery',
    paymentGuaranteed: false,
    budgetMin: 35000, budgetMax: 40000,
  },
  {
    loadId: 'CL003', isNew: true,
    pickupCity: 'Chennai, TN',
    dropCity: 'Mumbai, MH',
    pickupFullAddress: 'Survey 14, Manali Industrial Area, Chennai 600068',
    dropFullAddress: 'Unit 7, Bhiwandi Warehouse Complex, Mumbai 421302',
    pickupDate: '30 Apr, 06:00 AM',
    vehicleCategory: 'trailer',
    vehicleType: 'Flat Bed Trailer',
    vehicleSize: '40ft',
    axle: '18 Wheeler',
    weight: 35, distance: 1337,
    goodsType: 'Steel Coils',
    paymentTerms: '85% Advance',
    paymentGuaranteed: true,
    budgetMin: 85000, budgetMax: 95000,
  },
  {
    loadId: 'CL004', isNew: false,
    pickupCity: 'Chennai, TN',
    dropCity: 'Coimbatore, TN',
    pickupFullAddress: 'No 8, Guindy Industrial Estate, Chennai 600032',
    dropFullAddress: 'Phase 2, SIDCO Industrial Estate, Coimbatore 641021',
    pickupDate: '28 Apr, 02:00 PM',
    vehicleCategory: 'lcv',
    vehicleType: 'LCV Open Body',
    vehicleSize: '19ft',
    axle: '4 Wheeler',
    weight: 5, distance: 495,
    goodsType: 'Textiles',
    paymentTerms: '70% Advance',
    paymentGuaranteed: false,
    budgetMin: 12000, budgetMax: 15000,
  },
  {
    loadId: 'CL005', isNew: true,
    pickupCity: 'Chennai, TN',
    dropCity: 'Delhi, DL',
    pickupFullAddress: 'Block B, Irungattukottai SEZ, Chennai 602105',
    dropFullAddress: 'Kundli Industrial Area, Sonipat, Delhi NCR 131028',
    pickupDate: '29 Apr, 09:00 AM',
    vehicleCategory: 'industrial',
    vehicleType: 'Tanker',
    vehicleSize: '10tyres',
    axle: '10 Tyres',
    weight: 18, distance: 2180,
    goodsType: 'Chemical Liquid',
    paymentTerms: '90% Advance',
    paymentGuaranteed: true,
    budgetMin: 95000, budgetMax: 110000,
  },
  // ════════════════════════════════════════
  // MUMBAI LOADS
  // ════════════════════════════════════════
  {
    loadId: 'ML001', isNew: true,
    pickupCity: 'Mumbai, MH',
    dropCity: 'Bengaluru, KA',
    pickupFullAddress: 'Plot A4, Bhiwandi Logistics Park, Thane 421302',
    dropFullAddress: 'Sy No 88, Hoskote Industrial Area, Bengaluru 562114',
    pickupDate: '28 Apr, 07:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Half/Full Body',
    vehicleSize: '24ft',
    axle: '10 Wheeler',
    weight: 15, distance: 984,
    goodsType: 'Automotive Parts',
    paymentTerms: '85% Advance',
    paymentGuaranteed: true,
    budgetMin: 45000, budgetMax: 52000,
  },
  {
    loadId: 'ML002', isNew: true,
    pickupCity: 'Mumbai, MH',
    dropCity: 'Pune, MH',
    pickupFullAddress: 'Sector 5, Taloja MIDC, Navi Mumbai 410208',
    dropFullAddress: 'Gat No 234, Chakan MIDC, Pune 410501',
    pickupDate: '28 Apr, 11:00 AM',
    vehicleCategory: 'mini',
    vehicleType: 'Pickup Open',
    vehicleSize: 'Dost 2T',
    axle: '4 Wheeler',
    weight: 2, distance: 148,
    goodsType: 'Electronics',
    paymentTerms: '100% Advance',
    paymentGuaranteed: true,
    budgetMin: 4500, budgetMax: 5500,
  },
  {
    loadId: 'ML003', isNew: false,
    pickupCity: 'Mumbai, MH',
    dropCity: 'Hyderabad, TS',
    pickupFullAddress: 'Unit 12, Mahape MIDC, Navi Mumbai 400710',
    dropFullAddress: 'Plot 9, Pashamylaram Industrial Area, Hyderabad 502307',
    pickupDate: '29 Apr, 05:00 AM',
    vehicleCategory: 'container',
    vehicleType: 'Standard Container',
    vehicleSize: '32ft MXL',
    axle: 'Multi Axle',
    weight: 18, distance: 710,
    goodsType: 'Packaged Foods',
    paymentTerms: '75% Advance',
    paymentGuaranteed: false,
    budgetMin: 38000, budgetMax: 44000,
  },
  {
    loadId: 'ML004', isNew: true,
    pickupCity: 'Mumbai, MH',
    dropCity: 'Nagpur, MH',
    pickupFullAddress: 'G-14, Rabale MIDC, Navi Mumbai 400701',
    dropFullAddress: 'Plot 44, Butibori MIDC, Nagpur 441122',
    pickupDate: '30 Apr, 08:00 AM',
    vehicleCategory: 'trailer',
    vehicleType: 'Dala Body Trailer',
    vehicleSize: '40t',
    axle: '18 Wheeler',
    weight: 40, distance: 830,
    goodsType: 'Construction Material',
    paymentTerms: '80% Advance',
    paymentGuaranteed: true,
    budgetMin: 55000, budgetMax: 65000,
  },
  {
    loadId: 'ML005', isNew: false,
    pickupCity: 'Mumbai, MH',
    dropCity: 'Chennai, TN',
    pickupFullAddress: 'Shed 3, Pirangut Industrial Zone, Pune 412115',
    dropFullAddress: 'Plot 12, Manali New Town, Chennai 600068',
    pickupDate: '29 Apr, 06:00 AM',
    vehicleCategory: 'lcv',
    vehicleType: 'LCV Container',
    vehicleSize: '20ft',
    axle: '6 Wheeler',
    weight: 7, distance: 1337,
    goodsType: 'Pharma Products',
    paymentTerms: '90% Advance',
    paymentGuaranteed: true,
    budgetMin: 28000, budgetMax: 33000,
  },
  // ════════════════════════════════════════
  // BENGALURU LOADS
  // ════════════════════════════════════════
  {
    loadId: 'BL001', isNew: true,
    pickupCity: 'Bengaluru, KA',
    dropCity: 'Chennai, TN',
    pickupFullAddress: 'Plot 23, KIADB Industrial Area, Hoskote, Bengaluru 562114',
    dropFullAddress: 'No 5, Ambattur Industrial Estate, Chennai 600058',
    pickupDate: '28 Apr, 09:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Body',
    vehicleSize: '20ft',
    axle: '6 Wheeler',
    weight: 10, distance: 346,
    goodsType: 'Garments',
    paymentTerms: '85% Advance',
    paymentGuaranteed: false,
    budgetMin: 18000, budgetMax: 22000,
  },
  {
    loadId: 'BL002', isNew: false,
    pickupCity: 'Bengaluru, KA',
    dropCity: 'Hyderabad, TS',
    pickupFullAddress: 'Shed 9, Bommasandra Industrial Area, Bengaluru 560099',
    dropFullAddress: 'IDA Phase 3, Cherlapally, Hyderabad 500051',
    pickupDate: '29 Apr, 07:30 AM',
    vehicleCategory: 'container',
    vehicleType: 'Standard Container',
    vehicleSize: '24ft',
    axle: 'Single Axle',
    weight: 9, distance: 563,
    goodsType: 'IT Equipment',
    paymentTerms: '100% Advance',
    paymentGuaranteed: true,
    budgetMin: 25000, budgetMax: 30000,
  },
  {
    loadId: 'BL003', isNew: true,
    pickupCity: 'Bengaluru, KA',
    dropCity: 'Mumbai, MH',
    pickupFullAddress: 'Gate 1, Peenya Industrial Area, Bengaluru 560058',
    dropFullAddress: 'Plot A4, Bhiwandi Logistics Park, Thane 421302',
    pickupDate: '30 Apr, 05:00 AM',
    vehicleCategory: 'industrial',
    vehicleType: 'Tipper',
    vehicleSize: '10tyres',
    axle: '10 Tyres',
    weight: 16, distance: 984,
    goodsType: 'Sand & Aggregate',
    paymentTerms: '70% Advance',
    paymentGuaranteed: false,
    budgetMin: 42000, budgetMax: 50000,
  },
  // ════════════════════════════════════════
  // HYDERABAD LOADS
  // ════════════════════════════════════════
  {
    loadId: 'HL001', isNew: true,
    pickupCity: 'Hyderabad, TS',
    dropCity: 'Chennai, TN',
    pickupFullAddress: 'Plot 7, IDA Uppal, Hyderabad 500039',
    dropFullAddress: 'No 3, Guindy Industrial Estate, Chennai 600032',
    pickupDate: '28 Apr, 08:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Body',
    vehicleSize: '22ft',
    axle: '10 Wheeler',
    weight: 18, distance: 627,
    goodsType: 'Rice Bags',
    paymentTerms: '80% Advance',
    paymentGuaranteed: true,
    budgetMin: 28000, budgetMax: 34000,
  },
  {
    loadId: 'HL002', isNew: false,
    pickupCity: 'Hyderabad, TS',
    dropCity: 'Delhi, DL',
    pickupFullAddress: 'Phase 2, Pashamylaram Industrial Area, Hyderabad 502307',
    dropFullAddress: 'Plot 14, Kundli Industrial Area, Delhi NCR 131028',
    pickupDate: '29 Apr, 04:00 AM',
    vehicleCategory: 'trailer',
    vehicleType: 'Flat Bed Trailer',
    vehicleSize: '40ft',
    axle: '18 Wheeler',
    weight: 30, distance: 1567,
    goodsType: 'Heavy Machinery',
    paymentTerms: '85% Advance',
    paymentGuaranteed: true,
    budgetMin: 90000, budgetMax: 105000,
  },
  {
    loadId: 'HL003', isNew: true,
    pickupCity: 'Hyderabad, TS',
    dropCity: 'Bengaluru, KA',
    pickupFullAddress: 'Shed 14, IDA Cherlapally, Hyderabad 500051',
    dropFullAddress: 'Plot 7, Whitefield Industrial Area, Bengaluru 560066',
    pickupDate: '28 Apr, 11:00 AM',
    vehicleCategory: 'mini',
    vehicleType: 'Mini Container',
    vehicleSize: 'Tata Ace 1T',
    axle: '4 Wheeler',
    weight: 1, distance: 563,
    goodsType: 'Medical Supplies',
    paymentTerms: '100% Advance',
    paymentGuaranteed: true,
    budgetMin: 8000, budgetMax: 10000,
  },
  // ════════════════════════════════════════
  // NAGPUR LOADS
  // ════════════════════════════════════════
  {
    loadId: 'NL001', isNew: true,
    pickupCity: 'Nagpur, MH',
    dropCity: 'Mumbai, MH',
    pickupFullAddress: 'Plot 88, Butibori MIDC, Nagpur 441122',
    dropFullAddress: 'Sector 3, Taloja MIDC, Navi Mumbai 410208',
    pickupDate: '28 Apr, 06:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Body',
    vehicleSize: '24ft',
    axle: '12 Wheeler',
    weight: 22, distance: 830,
    goodsType: 'Cotton Bales',
    paymentTerms: '75% Advance',
    paymentGuaranteed: false,
    budgetMin: 32000, budgetMax: 38000,
  },
  {
    loadId: 'NL002', isNew: false,
    pickupCity: 'Nagpur, MH',
    dropCity: 'Hyderabad, TS',
    pickupFullAddress: 'Gat 44, Hingna MIDC, Nagpur 440028',
    dropFullAddress: 'IDA Phase 1, Uppal, Hyderabad 500039',
    pickupDate: '29 Apr, 08:00 AM',
    vehicleCategory: 'industrial',
    vehicleType: 'Bulker',
    vehicleSize: '12tyres',
    axle: '12 Tyres',
    weight: 24, distance: 503,
    goodsType: 'Cement Powder',
    paymentTerms: '85% Advance',
    paymentGuaranteed: true,
    budgetMin: 22000, budgetMax: 28000,
  },
  // ════════════════════════════════════════
  // DELHI LOADS
  // ════════════════════════════════════════
  {
    loadId: 'DL001', isNew: true,
    pickupCity: 'Delhi, DL',
    dropCity: 'Mumbai, MH',
    pickupFullAddress: 'Plot 22, Udyog Vihar Phase 4, Gurugram 122015',
    dropFullAddress: 'Unit 8, Bhiwandi Warehouse Complex, Thane 421302',
    pickupDate: '28 Apr, 05:00 AM',
    vehicleCategory: 'trailer',
    vehicleType: 'Dala Body Trailer',
    vehicleSize: '43t',
    axle: '18 Wheeler',
    weight: 43, distance: 1415,
    goodsType: 'Steel Rods',
    paymentTerms: '80% Advance',
    paymentGuaranteed: true,
    budgetMin: 95000, budgetMax: 115000,
  },
  {
    loadId: 'DL002', isNew: false,
    pickupCity: 'Delhi, DL',
    dropCity: 'Chennai, TN',
    pickupFullAddress: 'Sector 58, Noida Industrial Area, UP 201301',
    dropFullAddress: 'Phase 1, SIPCOT, Irrungattukottai, Chennai 602105',
    pickupDate: '29 Apr, 04:00 AM',
    vehicleCategory: 'container',
    vehicleType: 'Standard Container',
    vehicleSize: '32ft TXL',
    axle: 'Triple Axle',
    weight: 25, distance: 2180,
    goodsType: 'Consumer Goods',
    paymentTerms: '90% Advance',
    paymentGuaranteed: true,
    budgetMin: 110000, budgetMax: 130000,
  },
  {
    loadId: 'DL003', isNew: true,
    pickupCity: 'Delhi, DL',
    dropCity: 'Bengaluru, KA',
    pickupFullAddress: 'A-45, Okhla Industrial Area Phase 2, Delhi 110020',
    dropFullAddress: 'Shed 6, Electronic City Phase 1, Bengaluru 560100',
    pickupDate: '30 Apr, 06:00 AM',
    vehicleCategory: 'lcv',
    vehicleType: 'LCV Container',
    vehicleSize: '22ft',
    axle: '6 Wheeler',
    weight: 6, distance: 2150,
    goodsType: 'Mobile Phones',
    paymentTerms: '100% Advance',
    paymentGuaranteed: true,
    budgetMin: 55000, budgetMax: 65000,
  },
  // ════════════════════════════════════════
  // COIMBATORE LOADS
  // ════════════════════════════════════════
  {
    loadId: 'CoL001', isNew: true,
    pickupCity: 'Coimbatore, TN',
    dropCity: 'Chennai, TN',
    pickupFullAddress: 'Phase 2, SIDCO Industrial Estate, Coimbatore 641021',
    dropFullAddress: 'Plot 3, Ambattur Industrial Estate, Chennai 600058',
    pickupDate: '28 Apr, 09:00 AM',
    vehicleCategory: 'open',
    vehicleType: 'Open Body',
    vehicleSize: '17ft',
    axle: '6 Wheeler',
    weight: 7.5, distance: 495,
    goodsType: 'Textile Machinery',
    paymentTerms: '80% Advance',
    paymentGuaranteed: false,
    budgetMin: 14000, budgetMax: 18000,
  },
  {
    loadId: 'CoL002', isNew: false,
    pickupCity: 'Coimbatore, TN',
    dropCity: 'Bengaluru, KA',
    pickupFullAddress: 'Ganapathy Industrial Estate, Coimbatore 641006',
    dropFullAddress: 'KIADB Phase 3, Peenya, Bengaluru 560058',
    pickupDate: '29 Apr, 07:00 AM',
    vehicleCategory: 'mini',
    vehicleType: 'Mini Open',
    vehicleSize: 'Tata Ace 1T',
    axle: '4 Wheeler',
    weight: 1, distance: 360,
    goodsType: 'Spare Parts',
    paymentTerms: '100% Advance',
    paymentGuaranteed: true,
    budgetMin: 6000, budgetMax: 8000,
  },
  // ════════════════════════════════════════
  // PUNE LOADS
  // ════════════════════════════════════════
  {
    loadId: 'PL001', isNew: true,
    pickupCity: 'Pune, MH',
    dropCity: 'Delhi, DL',
    pickupFullAddress: 'E-12, Chakan MIDC Phase 2, Pune 410501',
    dropFullAddress: 'Plot 33, Manesar Industrial Zone, Gurugram 122051',
    pickupDate: '28 Apr, 04:00 AM',
    vehicleCategory: 'trailer',
    vehicleType: 'Flat Bed Trailer',
    vehicleSize: '35ft',
    axle: '16 Wheeler',
    weight: 33, distance: 1478,
    goodsType: 'Two Wheelers',
    paymentTerms: '85% Advance',
    paymentGuaranteed: true,
    budgetMin: 78000, budgetMax: 90000,
  },
  {
    loadId: 'PL002', isNew: false,
    pickupCity: 'Pune, MH',
    dropCity: 'Nagpur, MH',
    pickupFullAddress: 'Gut 101, Ranjangaon MIDC, Pune 412220',
    dropFullAddress: 'Plot 12, Hingna MIDC, Nagpur 440028',
    pickupDate: '29 Apr, 09:00 AM',
    vehicleCategory: 'industrial',
    vehicleType: 'Tipper',
    vehicleSize: '10tyres',
    axle: '10 Tyres',
    weight: 15, distance: 235,
    goodsType: 'Gravel & Stone',
    paymentTerms: '70% Advance',
    paymentGuaranteed: false,
    budgetMin: 12000, budgetMax: 16000,
  },
];
